server:
  port: 8080

spring:
  application:
    name: community

  datasource:
    url: "${DB_URL}"
    username: "${DB_NAME}"
    password: "${DB_PWD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    header: Authorization
    secret: "${JWT_SECRET}"
    token-validity-in-seconds: "${JWT_VALIDITY_SECONDS}"